Update swift coverage conversion script for Xcode 13 and 14
SonarSource/sonar-scanning-examples pull request #151
Opened 2023-01-23 16:03 UTC by francoismora

2023-01-30 13:59 UTC, vilchik-elena requested changes

2023-01-30 13:59 UTC, vilchik-elena commented on swift-coverage/swift-coverage-example/xccov-to-sonarqube-generic.sh
> +function convert_archive {
inline

2023-01-30 13:59 UTC, vilchik-elena commented on swift-coverage/swift-coverage-example/xccov-to-sonarqube-generic.sh
> +    elif (( xcode_version < 13 )); then
pull up to global scope

2023-01-30 13:59 UTC, vilchik-elena commented on swift-coverage/README.md
> +This example demonstrates how to import Xcode Coverage data (aka ProfData) to SonarQube for a Swift project. It supports Xcode 13 and above.
drop `(aka ProfData)`

2023-01-30 13:59 UTC, vilchik-elena commented on swift-coverage/README.md
> +* [SonarQube](http://www.sonarqube.org/downloads/) 9.8 or Latest
keep old LTS

2023-01-30 13:59 UTC, vilchik-elena commented on swift-coverage/README.md
> +* [SonarQube](http://www.sonarqube.org/downloads/) 9.8 or Latest
and above

2023-01-30 13:59 UTC, vilchik-elena commented on swift-coverage/README.md
> +* [SonarQube Scanner](http://docs.sonarqube.org/display/SCAN/Analyzing+with+SonarQube+Scanner) 4.8+
no need update the version

2023-01-30 13:59 UTC, vilchik-elena commented on swift-coverage/swift-coverage-example/xccov-to-sonarqube-generic.sh
> +      echo "Incorrect test results path. Required *.xcresult: $xccovarchive_file" 1>&2;
`Expecting input to match "*.xcresult", got ...`

2023-01-30 13:59 UTC, vilchik-elena commented on swift-coverage/README.md
> +stored in `*.xcresult` folders to a SonarQube generic XML file and then pass it
link to docs about generic coverage format

2023-01-30 13:59 UTC, vilchik-elena commented on swift-coverage/README.md
> +stored in `*.xcresult` folders to a SonarQube generic XML file and then pass it
`a SonarQube generic test coverage format`

2023-01-30 13:59 UTC, vilchik-elena commented on swift-coverage/README.md
> +stored in `*.xcresult` folders to a SonarQube generic XML file and then pass it
drop `and then pass ....`

2023-01-30 13:59 UTC, vilchik-elena commented on swift-coverage/swift-coverage-example/xccov-to-sonarqube-generic.sh
>    for xccovarchive_file in "$@"; do
let's drop the loop

2023-01-30 13:59 UTC, vilchik-elena commented on swift-coverage/README.md
> +when executing sonar-scanner:
`Use property bla-bla to reference the generated coverage report`

2023-01-30 13:59 UTC, vilchik-elena commented on swift-coverage/README.md
> +sonar-scanner -Dsonar.projectKey=TestCoverage -Dsonar.coverageReportPaths=Coverage.xml
remove projectkey

2023-01-30 13:59 UTC, vilchik-elena commented on swift-coverage/README.md
> +coverage for the application executable and the dynamic library binaries. For
new line before `For...`

2023-01-30 13:59 UTC, vilchik-elena commented on swift-coverage/README.md
> +the project example, you can use the following command where `<id>` should
use the same wording as for xccov

2023-01-30 13:59 UTC, vilchik-elena commented on swift-coverage/README.md
> +sonar-scanner -Dsonar.projectKey=TestCoverage -Dsonar.sources=. -Dsonar.swift.coverage.reportPaths=Coverage.report
drop sources, drop projectKey

2023-01-30 13:59 UTC, vilchik-elena commented on swift-coverage/README.md
>  2. Verify that for the project "swift-coverage-example" the coverage value is > 65%.
`is around 75%`

2023-01-30 14:54 UTC, francoismora commented on swift-coverage/swift-coverage-example/xccov-to-sonarqube-generic.sh
> +function convert_archive {
Done

2023-01-30 14:54 UTC, francoismora commented on swift-coverage/swift-coverage-example/xccov-to-sonarqube-generic.sh
> +    elif (( xcode_version < 13 )); then
Done

2023-01-30 14:54 UTC, francoismora commented on swift-coverage/README.md
> +This example demonstrates how to import Xcode Coverage data (aka ProfData) to SonarQube for a Swift project. It supports Xcode 13 and above.
Done

2023-01-30 14:55 UTC, francoismora commented on swift-coverage/README.md
> +* [SonarQube Scanner](http://docs.sonarqube.org/display/SCAN/Analyzing+with+SonarQube+Scanner) 4.8+
Reverted

2023-01-30 14:55 UTC, francoismora commented on swift-coverage/swift-coverage-example/xccov-to-sonarqube-generic.sh
> +      echo "Incorrect test results path. Required *.xcresult: $xccovarchive_file" 1>&2;
Done

2023-01-31 15:48 UTC, vilchik-elena requested changes

2023-01-31 15:48 UTC, vilchik-elena commented on swift-coverage/README.md
> +This example demonstrates how to import Xcode Coverage data to SonarQube for a Swift project. It supports Xcode 13 and above.
`13` -> `13.3`
And I would move this to the prerequisites section

2023-01-31 15:48 UTC, vilchik-elena commented on swift-coverage/README.md
> +bash xccov-to-sonarqube-generic.sh Build/Logs/Test/Run-swift-coverage-example-2023.01.27_16-07-44-+0100.xcresult >Coverage.xml
let's add `/` after`.xcresult` to be explicit that it's kind of dir :)

2023-01-31 15:48 UTC, vilchik-elena commented on swift-coverage/README.md
> +SonarQube format using the script as in the following example:
```suggestion
First, locate the Xcode test result folder (`*.xcresult`). Then use it as a parameter to the script converting the coverage data to the SonarQube format as in the following example:
```

2023-01-31 15:48 UTC, vilchik-elena commented on swift-coverage/README.md
> +following example:
```suggestion
In the case of the project example, first, locate the `Coverage.profdata` file
under the `ProfileData` folder. Then, generate an `llvm-cov` report as in the
following example (the located `Coverage.profdata` file should be the value of `-instr-profile` parameter):
```

2023-01-31 15:48 UTC, vilchik-elena commented on swift-coverage/swift-coverage-example/xccov-to-sonarqube-generic.sh
> +  echo "Xcode version '$xcode_version' not supported version 13.3 or above is required" 1>&2;
some punctuator is missing?
```suggestion
  echo "Xcode version '$xcode_version' not supported, version 13.3 or above is required" 1>&2;
```

2023-02-02 08:37 UTC, vilchik-elena approved these changes

2023-02-02 08:38 UTC, merged